# Generated by Django 3.0.6 on 2020-05-28 06:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_company_tag_dict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_viewed',
            field=models.ManyToManyField(blank=True, null=True, related_name='viewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
