# Generated by Django 3.0.5 on 2020-05-14 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20200514_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(null=True),
        ),
    ]
