# Generated by Django 3.0.6 on 2020-05-28 06:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20200528_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_viewed',
            field=models.ManyToManyField(related_name='viewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
