# Generated by Django 3.0.6 on 2020-05-14 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0003_auto_20200514_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='mainapp.Company'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_liked',
            field=models.ManyToManyField(blank=True, null=True, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_post',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='mainapp.Post'),
        ),
    ]
