# Generated by Django 3.0.6 on 2020-05-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200527_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
