# Generated by Django 3.0.6 on 2020-05-27 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0004_post_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_liked',
            field=models.ManyToManyField(related_name='liked_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_viewed',
        ),
        migrations.AddField(
            model_name='post',
            name='is_viewed',
            field=models.ManyToManyField(related_name='viewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
