# Generated by Django 3.0.6 on 2020-06-01 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_auto_20200601_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='is_viewed',
            field=models.ManyToManyField(blank=True, related_name='viewed_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
