# Generated by Django 3.0.6 on 2020-06-03 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20200601_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tag_dict',
        ),
    ]
